version: '3.7'

services:
  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    ports:
      - "3000:3000"
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: railway
      MB_DB_PORT: 22677
      MB_DB_USER: postgres
      MB_DB_PASS: fZhbIUHSvmPabFtynDIqipBHaBJlwYtA
      MB_DB_HOST: yamanote.proxy.rlwy.net
    restart: unless-stopped
    volumes:
      - metabase-data:/metabase-data

volumes:
  metabase-data:
